### ISSUE TITLE
服务器配置好后运行报错

### ISSUE THREAD

**Issue by hqgordon** [abc123lzf/flyingsocks#7]
![image](https://user-images.githubusercontent.com/53546418/143664850-aaa8446c-04eb-42b2-b23f-24b082e53fb1.png)
2021-11-27 09:42:22,781 ClientProcessor [main] (AbstractComponent.java:192) ERROR --> Component [ProxyRequestProcessor [ClientProcessor]] init failure.
java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:473)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:497)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:488)
	at com.lzf.flyingsocks.server.core.client.ProxyRequestProcessor.initInternal(ProxyRequestProcessor.java:116)
	at com.lzf.flyingsocks.LifecycleBase.init(LifecycleBase.java:54)
	at com.lzf.flyingsocks.AbstractComponent.initInternal(AbstractComponent.java:190)
	at com.lzf.flyingsocks.server.core.client.ClientProcessor.initInternal(ClientProcessor.java:121)
	at com.lzf.flyingsocks.LifecycleBase.init(LifecycleBase.java:54)
	at com.lzf.flyingsocks.AbstractComponent.initInternal(AbstractComponent.java:190)
	at com.lzf.flyingsocks.server.core.ProxyProcessor.initInternal(ProxyProcessor.java:133)
	at com.lzf.flyingsocks.LifecycleBase.init(LifecycleBase.java:54)
	at com.lzf.flyingsocks.AbstractComponent.initInternal(AbstractComponent.java:190)
	at com.lzf.flyingsocks.server.StandardServer.initInternal(StandardServer.java:81)
	at com.lzf.flyingsocks.LifecycleBase.init(LifecycleBase.java:54)
	at com.lzf.flyingsocks.server.ServerBoot.boot(ServerBoot.java:62)
	at com.lzf.flyingsocks.server.ServerBoot.main(ServerBoot.java:49)

**Comment by abc123lzf** [comment]
@hqgordon 应该是channelType和eventLoop不匹配的问题，麻烦再尝试一下v3.0分支最新提交的版本？
